#define NUM_INTERCEPTED_CALLS 5

#define FUNC_OPEN  0
#define FUNC_LSEEK 1
#define FUNC_CLONE 2
#define FUNC_CLOSE 3
#define FUNC_WRITE 4

#define POS_SYSCALL_READ 3
#define POS_SYSCALL_WRITE 4
#define POS_SYSCALL_OPEN 5
#define POS_SYSCALL_CLOSE 6
#define POS_SYSCALL_CLONE 120
#define POS_SYSCALL_LSEEK 140